<a href="https://colab.research.google.com/github/RientArlCroud/Challenge-4-telecom-X-2-an-lisis-de-datos/blob/main/Challenge_4_an%C3%A1lisis_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Challenge 3 Análisis de datos, empresa de telecomunicaciones Telecom X

proceso de modelado para identificar posibles cancelaciones del servicio.

In [3]:
import pandas as pd

Lectura de datos

In [4]:
df = pd.read_csv('/content/telecom.csv')

In [5]:
df

,customer_id,churn,customer_gender,customer_senior_citizen,customer_partner,customer_dependents,customer_tenure,phone_phone_service,phone_multiple_lines,internet_internet_service,...,internet_streaming_tv,internet_streaming_movies,account_contract,account_paperless_billing,account_payment_method,account_charges_monthly,account_charges_total,cuentas_diarias,tenure_group,charges_monthly_group
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,One year,Yes,Mailed check,65.60,593.30,2.186667,"(6, 12]","(54, 66]"
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,Yes,Month-to-month,No,Mailed check,59.90,542.40,1.996667,"(6, 12]","(54, 66]"
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,No,Month-to-month,Yes,Electronic check,73.90,280.85,2.463333,"(0, 6]","(66, 78]"
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85,3.266667,"(12, 24]","(90, 102]"
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40,2.796667,"(0, 6]","(78, 90]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,One year,No,Mailed check,55.15,742.90,1.838333,"(12, 24]","(54, 66]"
7028,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70,2.836667,"(12, 24]","(78, 90]"
7029,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,No,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.676667,"(0, 6]","(42, 54]"
7030,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Two year,No,Mailed check,67.85,4627.65,2.261667,"(48, 72]","(66, 78]"
7031,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,Two year,No,Electronic check,59.00,3707.60,1.966667,"(48, 72]","(54, 66]"

Retiro de columnas innecesarias

In [6]:
df.drop(columns=['customer_id','cuentas_diarias', 'tenure_group', 'charges_monthly_group'], axis=1, inplace=True)

In [7]:
df

,churn,customer_gender,customer_senior_citizen,customer_partner,customer_dependents,customer_tenure,phone_phone_service,phone_multiple_lines,internet_internet_service,internet_online_security,internet_online_backup,internet_device_protection,internet_tech_support,internet_streaming_tv,internet_streaming_movies,account_contract,account_paperless_billing,account_payment_method,account_charges_monthly,account_charges_total
0,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30
1,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40
2,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,No,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90
7028,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70
7029,No,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7030,No,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7031,No,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60

Selección de variables explicativas y variable dependiente (objetivo)

In [21]:
X = df.drop(columns=['churn'], axis=1)
y = df['churn']

In [22]:
X

,customer_gender,customer_senior_citizen,customer_partner,customer_dependents,customer_tenure,phone_phone_service,phone_multiple_lines,internet_internet_service,internet_online_security,internet_online_backup,internet_device_protection,internet_tech_support,internet_streaming_tv,internet_streaming_movies,account_contract,account_paperless_billing,account_payment_method,account_charges_monthly,account_charges_total
0,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30
1,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40
2,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,Female,0,No,No,13,Yes,No,DSL,Yes,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90
7028,Male,0,Yes,No,22,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70
7029,Male,0,No,No,2,Yes,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7030,Male,0,Yes,Yes,67,Yes,No,DSL,Yes,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7031,Male,0,Yes,Yes,63,No,No phone service,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60

In [23]:
y

0        No
1        No
2       Yes
3       Yes
4       Yes
       ...
7027     No
7028    Yes
7029     No
7030     No
7031     No
Name: churn, Length: 7032, dtype: object

Proceso de encoding para las variables explicativas y la variable objetivo

In [24]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [25]:
columnas = X.columns
columnas

Index(['customer_gender', 'customer_senior_citizen', 'customer_partner',
       'customer_dependents', 'customer_tenure', 'phone_phone_service',
       'phone_multiple_lines', 'internet_internet_service',
       'internet_online_security', 'internet_online_backup',
       'internet_device_protection', 'internet_tech_support',
       'internet_streaming_tv', 'internet_streaming_movies',
       'account_contract', 'account_paperless_billing',
       'account_payment_method', 'account_charges_monthly',
       'account_charges_total'],
      dtype='object')

In [26]:
one_hot = make_column_transformer(
    (OneHotEncoder(drop='if_binary'), ['customer_gender', 'customer_partner', 'customer_dependents',
                                       'phone_phone_service', 'phone_multiple_lines', 'internet_internet_service',
                                       'internet_online_security', 'internet_online_backup', 'internet_device_protection',
                                       'internet_tech_support', 'internet_streaming_tv', 'internet_streaming_movies', 'account_contract',
                                       'account_paperless_billing', 'account_payment_method']),
    remainder = 'passthrough',
    sparse_threshold = 0,
    verbose_feature_names_out = True
)

In [27]:
X = one_hot.fit_transform(X)

In [16]:
one_hot.get_feature_names_out(columnas)

array(['customer_gender_Male', 'customer_partner_Yes',
       'customer_dependents_Yes', 'phone_phone_service_Yes',
       'phone_multiple_lines_No', 'phone_multiple_lines_No phone service',
       'phone_multiple_lines_Yes', 'internet_internet_service_DSL',
       'internet_internet_service_Fiber optic',
       'internet_internet_service_No', 'internet_online_security_No',
       'internet_online_security_No internet service',
       'internet_online_security_Yes', 'internet_online_backup_No',
       'internet_online_backup_No internet service',
       'internet_online_backup_Yes', 'internet_device_protection_No',
       'internet_device_protection_No internet service',
       'internet_device_protection_Yes', 'internet_tech_support_No',
       'internet_tech_support_No internet service',
       'internet_tech_support_Yes', 'internet_streaming_tv_No',
       'internet_streaming_tv_No internet service',
       'internet_streaming_tv_Yes', 'internet_streaming_movies_No',
       'internet_streaming_movies_No internet service',
       'internet_streaming_movies_Yes', 'account_contract_Month-to-month',
       'account_contract_One year', 'account_contract_Two year',
       'account_paperless_billing_Yes',
       'account_payment_method_Bank transfer (automatic)',
       'account_payment_method_Credit card (automatic)',
       'account_payment_method_Electronic check',
       'account_payment_method_Mailed check', 'customer_senior_citizen',
       'customer_tenure', 'account_charges_monthly',
       'account_charges_total'], dtype=object)

In [17]:
X

array([[0.00000e+00, 1.00000e+00, 1.00000e+00, ..., 9.00000e+00,
        6.56000e+01, 5.93300e+02],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 9.00000e+00,
        5.99000e+01, 5.42400e+02],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 4.00000e+00,
        7.39000e+01, 2.80850e+02],
       ...,
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 2.00000e+00,
        5.03000e+01, 9.27500e+01],
       [1.00000e+00, 1.00000e+00, 1.00000e+00, ..., 6.70000e+01,
        6.78500e+01, 4.62765e+03],
       [1.00000e+00, 1.00000e+00, 1.00000e+00, ..., 6.30000e+01,
        5.90000e+01, 3.70760e+03]])

In [18]:
pd.DataFrame(X, columns = one_hot.get_feature_names_out(columnas))

,customer_gender_Male,customer_partner_Yes,customer_dependents_Yes,phone_phone_service_Yes,phone_multiple_lines_No,phone_multiple_lines_No phone service,phone_multiple_lines_Yes,internet_internet_service_DSL,internet_internet_service_Fiber optic,internet_internet_service_No,...,account_contract_Two year,account_paperless_billing_Yes,account_payment_method_Bank transfer (automatic),account_payment_method_Credit card (automatic),account_payment_method_Electronic check,account_payment_method_Mailed check,customer_senior_citizen,customer_tenure,account_charges_monthly,account_charges_total
0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,9.0,65.60,593.30
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,59.90,542.40
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,4.0,73.90,280.85
3,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,13.0,98.00,1237.85
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,3.0,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,13.0,55.15,742.90
7028,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,22.0,85.10,1873.70
7029,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,2.0,50.30,92.75
7030,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,67.0,67.85,4627.65
7031,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,63.0,59.00,3707.60

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
label_encoder = LabelEncoder()

In [30]:
y = label_encoder.fit_transform(y)

In [31]:
y

array([0, 0, 1, ..., 0, 0, 0])

Observando si existe desvalance en la variable objetivo

In [34]:
df['churn'].value_counts()

churn
No     5163
Yes    1869
Name: count, dtype: int64

In [35]:
df['churn'].value_counts(normalize=True)

churn
No     0.734215
Yes    0.265785
Name: proportion, dtype: float64

Balanceando los datos

In [36]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss

In [37]:
oversampling = SMOTE()
undersampling = NearMiss()

In [40]:
X_balanceada_OS, y_balanceada_OS = oversampling.fit_resample(X, y)

In [42]:
pd.Series(y_balanceada_OS).value_counts()

0    5163
1    5163
Name: count, dtype: int64

In [43]:
X_balanceada_US, y_balanceada_US = undersampling.fit_resample(X, y)

In [44]:
pd.Series(y_balanceada_US).value_counts()

0    1869
1    1869
Name: count, dtype: int64